server:
  port: 8761

spring:
  application:
    name: pri-eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# register-with-eureka: 애플리케이션이 Eureka 서버에 자신을 등록할지를 결정
# true(기본값): 애플리케이션이 Eureka 서버에 자신을 등록
#  이는 Eureka 클라이언트가 Eureka 서버에 자신의 인스턴스를 등록하여 다른 서비스들이 이 인스턴스를 발견할 수 있도록 한다
# false: 애플리케이션이 Eureka 서버에 자신을 등록하지 않음
#  주로 Eureka 서버 자체의 설정에서 사용함. Eureka 서버는 다른 서버에 자신을 등록할 필요가 없기 때문이다

# fetch-registry: 애플리케이션이 Eureka 서버로부터 등록된 서비스들의 레지스트리를 주기적으로 가져올지를 결정
# true(기본값): 애플리케이션이 Eureka 서버로부터 레지스트리를 주기적으로 가져옴. 이를 통해 서비스 검색이 가능해짐
# false: 애플리케이션이 Eureka 서버로부터 레지스트리를 가져오지 않음
#  주로 Eureka 서버 자체의 설정에서 사용함. Eureka 서버는 다른 서버로부터 레지스트리를 가져올 필요가 없기 때문이다
